"""Emit the appendix tables from the result files, not from the prose.

Every number in Appendix B and C is read out of the JSON that produced it, so
the appendix can be regenerated and diffed against the paper. Two rules from
the verification checklist are enforced here rather than trusted:

  * An arm is (method, body_encoding, pack_4d_mode). All three are needed. An
    uncompressed run records a body encoding and a rank-4 mode as well, both
    inert for it, so dropping `method` merges C_STD into arm B wherever the two
    share a directory -- which they do, in `ppl_eval` at seed 42.
  * GSM8K accuracy is recomputed as 100 * n_correct / n_samples rather than
    read from `accuracy_pct`.

Usage:  python scripts/make_appendix_tables.py > /tmp/appendix.tex
"""
import glob
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MODEL = "meta-llama/Llama-3.2-3B-Instruct"

# (method, body_encoding, pack_4d_mode) -> (letter, description)
ARMS = {
    ("naive_fp4", "e2m1", "fp4"): ("A", "E2M1 body, blockwise 4-bit rank-4"),
    ("naive_fp4", "e2m1", "fp8"): ("B", "E2M1 body, FP8 rank-4"),
    ("standard",  None,   None):  ("C", "uncompressed"),
    ("naive_fp4", "int4", "fp4"): ("D", "INT4 body, blockwise 4-bit rank-4"),
    ("naive_fp4", "int4", "fp8"): ("E", "INT4 body, FP8 rank-4"),
    ("naive_fp4", "e2m1", "chan_int4"): ("F", "E2M1 body, per-channel INT4 rank-4"),
}


# One adapter predates the three config fields being recorded, so its arm
# cannot be resolved from `training_config`. It is attributed by the directory
# it was trained into, and the paper says so rather than presenting it as if it
# had been read off the config like every other row.
BY_DIRECTORY = {"naive4bit_int4": ("naive_fp4", "int4", "fp4")}


def arm_of(tc, adapter_path):
    """Resolve the arm, treating the two inert fields as inert for `standard`."""
    m = tc.get("method")
    if m == "standard":
        return ARMS[("standard", None, None)], False
    key = (m, tc.get("body_encoding"), tc.get("pack_4d_mode"))
    if key in ARMS:
        return ARMS[key], False
    d = os.path.basename(os.path.dirname(adapter_path))
    if key == (None, None, None) and d in BY_DIRECTORY:
        return ARMS[BY_DIRECTORY[d]], True
    return None, False


def collect():
    rows = {}
    for path in sorted(glob.glob(os.path.join(ROOT, "results", "ppl_*", "*.json"))):
        d = json.load(open(path))
        tc = d.get("training_config") or {}
        ap = (d.get("adapter_path") or "").replace("/app/HMA_Project/", "")
        # A run whose config was never recorded has no n_train either, so the
        # length filter has to let it through and the directory has to vouch
        # for it.
        by_dir = os.path.basename(os.path.dirname(ap)) in BY_DIRECTORY
        if tc.get("model_id") != MODEL and not (by_dir and not tc):
            continue
        if tc and (tc.get("n_train") != 7473 or tc.get("epochs") != 2):
            continue
        a, inferred = arm_of(tc, ap)
        if a is None:
            continue
        # A seed measured twice is two runs, not one number measured twice: the
        # re-runs in section 5.3 are separate trainings. Only the original
        # enters the arm aggregate, and the file name carries the tag.
        tag = os.path.basename(path)
        member = ("_rerun_" not in tag and "_dup_" not in tag)
        rows.setdefault(ap, {
            "arm": a[0], "desc": a[1], "seed": tc.get("seed") or d.get("seed"),
            "wikitext": d.get("wikitext2_ppl"), "gsm8k_ppl": d.get("gsm8k_test_ppl"),
            "ppl_file": os.path.relpath(path, ROOT), "acc": None, "acc_file": None,
            "member": member, "inferred": inferred,
        })
    for path in sorted(glob.glob(os.path.join(
            ROOT, "results", "reeval_stop_mnt512_n200", "*.json"))):
        r = json.load(open(path))
        ap = (r.get("adapter_path") or "").replace("/app/HMA_Project/", "")
        if ap in rows:
            res = r["results"]
            rows[ap]["acc"] = 100.0 * res["n_correct"] / res["n_samples"]
            rows[ap]["acc_file"] = os.path.relpath(path, ROOT)
    return rows


def esc(s):
    return s.replace("_", r"\_")


def main():
    rows = collect()
    order = {"A": 0, "B": 1, "C": 2, "D": 3, "E": 4, "F": 5}
    items = sorted(rows.items(),
                   key=lambda kv: (order[kv[1]["arm"]], not kv[1]["member"],
                                  kv[1]["wikitext"]))

    print("%% generated by scripts/make_appendix_tables.py -- do not hand-edit")
    print("%% runs:", len(items))
    for arm in "ABCDEF":
        n = sum(1 for _, v in items if v["arm"] == arm)
        vals = [v["wikitext"] for _, v in items if v["arm"] == arm]
        print(f"%%   arm {arm}: n={n}  wikitext {min(vals):.4f}--{max(vals):.4f}")

    print(r"\begin{longtable}{cllrrrl}")
    print(r"\caption{Every full-length Llama-3.2-3B run behind the paper's "
          r"aggregate statistics: 7{,}473 examples, two epochs, 3{,}736 "
          r"optimizer steps. WikiText-2 and GSM8K perplexity are token-level "
          r"over 200 chunks and 500 problems at a 512-token cap. Accuracy is "
          r"the unified re-evaluation at 200 problems with stop sequences, "
          r"recomputed as $100 \times n_{\mathrm{correct}}/n$; a dash means "
          r"the adapter was not in that re-evaluation. A dagger marks the "
          r"three runs excluded from the arm aggregates: they are re-trainings "
          r"of a seed that was already trained, discussed in "
          r"\S\ref{sec:lottery}, and counting them twice would understate the "
          r"very variance that section is about. Arms are resolved from "
          r"(method, body encoding, rank-4 mode) jointly; the one row marked "
          r"$\ddagger$ predates those fields being recorded and is attributed "
          r"by its output directory.}\\")
    print(r"\label{tab:allruns}\\")
    head = (r"& arm & seed & WikiText-2 & GSM8K ppl & acc.\ (\%) & adapter \\")
    print(r"\toprule"); print(head); print(r"\midrule"); print(r"\endfirsthead")
    print(r"\toprule"); print(head); print(r"\midrule"); print(r"\endhead")
    prev = None
    for ap, v in items:
        if prev is not None and v["arm"] != prev:
            print(r"\midrule")
        prev = v["arm"]
        acc = f"{v['acc']:.1f}" if v["acc"] is not None else "---"
        mark = "" if v["member"] else r"$\dagger$"
        if v["inferred"]:
            mark += r"$\ddagger$"
        short = os.path.basename(os.path.dirname(ap)) + "/\\dots\\ " + \
            os.path.basename(ap).split("__")[-1].replace("_adapter", "")
        print(f"{mark} & {v['arm']} & {v['seed']} & {v['wikitext']:.4f} & "
              f"{v['gsm8k_ppl']:.4f} & {acc} & "
              f"\\texttt{{\\scriptsize {esc(short)}}} \\\\")
    print(r"\bottomrule")
    print(r"\end{longtable}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
